version: "3"
services:
  sitespeed-chrome:
    image: ${DOCKER_REGISTRY}sitespeedio/sitespeed.io
    command: "--config ./config/config-chrome.json ./scripts/script.js --multi"
    container_name: sitespeed-chrome
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy},demo.app.io
    shm_size: 2g
    volumes:
      - ./performance/config:/sitespeed.io/config/
      - ./performance/scripts:/sitespeed.io/scripts/
      - ./performance/results/:/sitespeed.io/results/
  demo.app.io:
    image: ${DOCKER_REGISTRY}milieuinfo/node:13
    container_name: demo.app.io
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy},demo.app.io
    hostname: demo.app.io
    extra_hosts:
      - "repository.milieuinfo.be:${REPOSITORY_FIXED_IP}"
    working_dir: /home/node/app
    entrypoint: bash -c "npm install && npm run demo"
    volumes:
      - .:/home/node/app
